name: CI Docs Generation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Give permission to run the doc generation script
        run: chmod u+x ./etc/shell-scripts/run_scancode_version_compare.sh

      - name: Run Script
        run:  VERSION_OLD="30.1.0" VERSION_NEW="31.0.0b4" ./etc/shell-scripts/run_scancode_version_compare.sh
